version: "3.9"
services:
  my_nuxt_docker:
    build: .
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - app_dotnuxt:/app/.nuxt
    command: [yarn, dev]
    ports:
      - "8000:3000"

volumes:
  app_node_modules:
  app_dotnuxt: